
# Baseline ReID training on source
data:
  source_root: ./data/source
  target_root: ./data/target
  height: 256
  width: 128
  batch_size: 64
  num_workers: 4
model:
  backbone: resnet50
  embedding_dim: 2048
train:
  epochs: 60
  lr: 1e-3
  weight_decay: 5e-4
  triplet_margin: 0.3
  seed: 42
out:
  ckpt_dir: ./outputs/baseline
